service: alexa-skills-test

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
plugins:
  - ../

custom:
  alexa:
#    vendorId: ${env:AMAZON_VENDOR_ID}
#    clientId: ${env:AMAZON_CLIENT_ID}
#    clientSecret: ${env:AMAZON_CLIENT_SECRET}
    skills:
      - id: ${env:ALEXA_SKILL_ID}
        manifest:
          publishingInformation:
            locales:
              ja-JP:
                name: test3
          apis:
            custom: {}
        models:
          ja-JP:
            interactionModel:
              languageModel:
                invocationName: hello
                intents:
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []
                  - name: HelloWorldIntent
                    samples:
                    - hello
                    - say hello
                    - hello world
                    - hello my world
